### ISSUE TITLE
Incorrect formulae to get cents

### ISSUE THREAD

**Issue by SaltySousChef** [qiuxiang/react-native-tuner#2]
Many thanks for the template, tidy! 

Just a heads up, in your getCents method the Math.log values should have been multiplied together instead of divided by each other. This is why it's so hard to get the gauge to to the centre of the dial as its only displaying the correct value at exactly 0 cents.

**Comment by qiuxiang** [comment]
Thank you for your heads up,  but I don't think my implementation is wrong. 

https://github.com/qiuxiang/react-native-tuner/blob/a15071b3b70a2899ba1e4bb86af6210b5b7c5ab9/src/tuner.js#L79-L80

The formula used in the code to calculate the cents comes from [Cent (music)](https://en.wikipedia.org/wiki/Cent_(music)):

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/159bfdb6691028edd9aa55d0fb80b84bb7e6f6d2)

```javascript
const a = this.getStandardFrequency(note)
const b = frequency
const cents = 1200 * Math.log2(b / a)
// also equal
const cents = 1200 * Math.log(b / a) / Math.log(2)
```

**Comment by qiuxiang** [comment]
In fact, I often use my tuner app ([other](https://qiuxiang.github.io/tuner/app/)) to tune the guitar, and I don't think there is anything wrong with it.

**Comment by SaltySousChef** [comment]
Oh wow that is really nice! Your browser based one seems to work amazing for me and UI also looks great. 

Being of simple mind I had rewritten the formulae the other way around as it was in the article I had read thinking that it is that which made a difference. The only other thing I had changed was the animated's transition speed so I guess that is what appeared to get the dial more in sync with the audio on mobile. Apologies for wasting your time!
